version: '3'
services:
  client:
    container_name: client
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://localhost:5000
    volumes:
      - ./client:/app
    networks:
      - mynetwork
  localhost:
    container_name: backend
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://database:27017/mydatabase
    volumes:
      - ./server:/app
    networks:
      - mynetwork
  database:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=mydatabase
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
